# Generated by Django 5.1.5 on 2025-02-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monnaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
