# Generated by Django 5.1.5 on 2025-02-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='intervals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='strategy',
            name='use_bollinger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='use_macd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='use_rsi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='use_stoch_rsi',
            field=models.BooleanField(default=False),
        ),
    ]
