# Generated by Django 5.1.5 on 2025-02-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='bollinger_middle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='stoch_rsi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
