# Generated by Django 5.1.5 on 2025-02-02 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_indicator_bollinger_middle_indicator_stoch_rsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('buy_conditions', models.JSONField(default=dict)),
                ('sell_conditions', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole', models.CharField(max_length=20)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.strategy')),
            ],
        ),
    ]
