# Generated by Django 5.1.5 on 2025-02-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tradelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolstrategy',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symbolstrategy',
            name='investment_amount',
            field=models.FloatField(default=100.0),
        ),
    ]
