# Generated by Django 5.1.5 on 2025-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_symbolstrategy_close_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='trade_result',
        ),
        migrations.AddField(
            model_name='tradelog',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='prix_actuel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='prix_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='strategy_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
