# Generated by Django 5.1.5 on 2025-02-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tradelog_investment_amount_tradelog_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'API (ex: Binance)", max_length=50, unique=True)),
                ('api_key', models.CharField(help_text='Clé API', max_length=255)),
                ('secret_key', models.CharField(help_text='Clé Secrète', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
