# Generated by Django 5.1.5 on 2025-02-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tradelog_prix_achat_alter_tradelog_prix_actuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monnaie',
            name='init',
            field=models.BooleanField(default=False),
        ),
    ]
