# Generated by Django 5.1.5 on 2025-02-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_monnaie_init'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CombinedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='buy_conditions',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='sell_conditions',
        ),
        migrations.AddField(
            model_name='indicator',
            name='rsiComb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='stochrsiComb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='strategy',
            name='combined_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.combinedtest'),
        ),
        migrations.CreateModel(
            name='IndicatorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=50)),
                ('interval', models.CharField(choices=[('1m', '1m'), ('3m', '3m'), ('5m', '5m'), ('15m', '15m'), ('1h', '1h'), ('4h', '4h'), ('1d', '1d')], max_length=5)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('>=', '>='), ('<=', '<='), ('==', '=='), ('!=', '!=')], max_length=2)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('threshold_indicator_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.indicatortest')),
            ],
        ),
        migrations.AddField(
            model_name='combinedtest',
            name='tests',
            field=models.ManyToManyField(blank=True, to='core.indicatortest'),
        ),
        migrations.DeleteModel(
            name='SymbolStrategy',
        ),
    ]
