# Generated by Django 5.1.5 on 2025-02-15 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_calculation_combinedtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='sub_calculations',
            field=models.ManyToManyField(blank=True, to='core.calculation'),
        ),
    ]
