# Generated by Django 5.1.5 on 2025-02-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_monnaie_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedtest',
            name='name',
            field=models.CharField(default='stoch_faible_1ma5m', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
