# Generated by Django 5.1.5 on 2025-02-15 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_combinedtest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortest',
            name='threshold_calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.calculation'),
        ),
    ]
