# Generated by Django 5.1.5 on 2025-02-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_indicatortest_threshold_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortest',
            name='name',
            field=models.CharField(default='1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
