# Generated by Django 5.1.5 on 2025-02-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_indicatortest_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='combined_test',
        ),
        migrations.AddField(
            model_name='strategy',
            name='buy_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_strategies', to='core.combinedtest'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sell_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_strategies', to='core.combinedtest'),
        ),
    ]
