# Generated by Django 5.1.5 on 2025-02-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_tradelog_strategy_json_tradelog_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedtest',
            name='sub_combined_tests',
            field=models.ManyToManyField(blank=True, to='core.combinedtest'),
        ),
    ]
